### ISSUE TITLE
Can't find the file repair method

### ISSUE THREAD

**Issue by yunkuangao** [NWYLZW/right-click-helper#10]
### ide : pycharm

> fix up:

![image](https://user-images.githubusercontent.com/40163747/116170461-78682e00-a739-11eb-99a0-e1e6df0c4350.png)
The working directory selects the project directory instead of src
![image](https://user-images.githubusercontent.com/40163747/116170639-c67d3180-a739-11eb-8ea4-c44fde01dd4c.png)

**Comment by NWYLZW** [comment]
😎
