### ISSUE TITLE
打开闪退

### ISSUE THREAD

**Issue by Ticysis** [NWYLZW/right-click-helper#9]
没有图片
因为就第一次打开的闪退提示了  "0x000......不能引用0x0000....,内存为read" 这条
后面打开就显示几秒钟页面,然后闪退
- win10 1909

**Comment by yunkuangao** [comment]
打开显示了一下主界面，然后直接闪退，没有任何报错

- win10 20H2

**Comment by NWYLZW** [comment]
> 没有图片
> 因为就第一次打开的闪退提示了 "0x000......不能引用0x0000....,内存为read" 这条
> 后面打开就显示几秒钟页面,然后闪退
> 
> * win10 1909

你用的是管理员权限打开的吗
如果没有的话，是否提示你用管理员权限打开？

**Comment by yunkuangao** [comment]
> > 没有图片
> > 因为就第一次打开的闪退提示了 "0x000......不能引用0x0000....,内存为read" 这条
> > 后面打开就显示几秒钟页面,然后闪退
> > 
> > * win10 1909
> 
> 你用的是管理员权限打开的吗
> 如果没有的话，是否提示你用管理员权限打开？

使用管理员一样，没什么区别

**Comment by NWYLZW** [comment]
> > > 没有图片
> > > 因为就第一次打开的闪退提示了 "0x000......不能引用0x0000....,内存为read" 这条
> > > 后面打开就显示几秒钟页面,然后闪退
> > > 
> > > * win10 1909
> > 
> > 
> > 你用的是管理员权限打开的吗
> > 如果没有的话，是否提示你用管理员权限打开？
> 
> 使用管理员一样，没什么区别

我这俩天抽个时间看看问题在哪，如果可以的话
提供一下日志信息，在项目根目录的log文件夹中

**Comment by Ticysis** [comment]
> 我这俩天抽个时间看看问题在哪，如果可以的话
> 提供一下日志信息，在项目根目录的log文件夹中
![Snipaste_2021-04-01_14-47-34](https://user-images.githubusercontent.com/39521717/113254556-52499c80-92f9-11eb-90be-db4cd6214034.png)
属实没有这个文件夹

**Comment by yunkuangao** [comment]
> > 我这俩天抽个时间看看问题在哪，如果可以的话
> > 提供一下日志信息，在项目根目录的log文件夹中
> > ![Snipaste_2021-04-01_14-47-34](https://user-images.githubusercontent.com/39521717/113254556-52499c80-92f9-11eb-90be-db4cd6214034.png)
> > 属实没有这个文件夹

![演示](https://user-images.githubusercontent.com/40163747/113472601-fa489c80-9496-11eb-8886-794988d16d08.gif)
正如gif的一样，并没有log文件夹

**Comment by NWYLZW** [comment]
我可能知道为什么了，因为没开vpn
可能会导致这个问题

**Comment by yunkuangao** [comment]
dev分支上解决了闪退问题，待合并到主分支
@NWYLZW 

问题已解决
